### ISSUE TITLE
Content-Proposals: section above Hub list

### ISSUE THREAD

**Issue by MartinSchott** [opencultureagency/ASKnet-Website#31]
Proposals for the following website section please in the comments.

![image](https://user-images.githubusercontent.com/8080649/140400921-ee383ad0-b6d8-4426-9568-65fca29e229f.png)

**Comment by Iamjaiksana** [comment]
#ASKnet is a capacity building and hub development program linking South Sudanese youth-led community hubs, be they in South Sudan or neighboring regions. The program started in 2015 with the creation of a community-based media training center,  Juba’s Open Knowledge and Innovation Hub ([jHUB](https://openculture.agency/innovation-hubs/)) which aimed to provide an open forum to discuss, identify, and develop solutions for South Sudan’s post-conflict challenges. Conflict flared up again at the end of 2016 and the jHUB community was dispersed. The program has since evolved into a collection of smaller hubs and local initiatives in South Sudan and Uganda known as #ASKnet.  This community continues to grow, move and intersect with other like-minded individuals and organizations at the grassroots and beyond creating opportunities for collaborations, training, and knowledge sharing. Meet the #ASKnet Hubs!

**Comment by timmwille** [comment]
> #ASKnet is a capacity building and hub development program linking South Sudanese youth-led community hubs, be they in South Sudan or neighboring regions. The program started in 2015 with the creation of a community-based media training center, Juba’s Open Knowledge and Innovation Hub ([jHUB](https://openculture.agency/innovation-hubs/)) which aimed to provide an open forum to discuss, identify, and develop solutions for South Sudan’s post-conflict challenges. Conflict flared up again at the end of 2016 and the jHUB community was dispersed. The program has since evolved into a collection of smaller hubs and local initiatives in South Sudan and Uganda known as #ASKnet. This community continues to grow, move and intersect with other like-minded individuals and organizations at the grassroots and beyond creating opportunities for collaborations, training, and knowledge sharing. Meet the #ASKnet Hubs!

That is quite long @Iamjaiksana but @MartinSchott maybe you can try how it looks? it sounds more like a history approach then a small subtitle/intro text to me. How many characters should this paragraph have ideally?

**Comment by Iamjaiksana** [comment]
I know it's lengthy, but that was my intention... Nothing on the website defines not only the project, but also the hubs and their stories more explicitly than 'a long text'... I asked two different people from the HUBs, and they both agreed that something like that would be beneficial on the website.

**Comment by MartinSchott** [comment]
Hey guys @Iamjaiksana @timmwille , 

I uploaded the text and also the other text blocks on the website, so it's live right now. So you can check if it looks good like that. In my opinion, the longer text blocks could use one or two separations / new paragraphs so it's easier to read. 

I also removed the overlays since it kind of hinders the impression on how everything will look, and we can communicate here in the issues or on telegram if any changes are requested.

**Comment by timmwille** [comment]
ok so this can be closed @Iamjaiksana ?

**Comment by timmwille** [comment]
done
