### ISSUE TITLE
Change the Timeline / History section 

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKnet-Website#47]
- [x] Link Content Issue template #38 
- [x] change timeline pictures (might be Beta)
- [x] Add Content (starting in early 2015 or even before? @intertwilight @yara89 )
- [x] change subtitle to "Projects, Trainings and Activities"

**Comment by timmwille** [comment]
@MartinSchott @bmen please reference this issue Link in Section timeline:
https://github.com/ASKnetCommunity/ASKnet.Community/issues/47

![image](https://user-images.githubusercontent.com/8081055/145091021-c0afe95a-af23-411c-9dbf-14bab88589ee.png)

**Comment by yara89** [comment]
small suggestion, was :

1. The program started in 2015 in South Sudan with the creation of a community-based media training center, Juba’s Open Knowledge and Innovation Hub (jHUB). The program has since evolved into a collection of smaller hubs and local initiatives in South Sudan and Uganda known as #ASKnet.
2. GoGirlsICT was founded in 2015 in Juba.
3. junubOS was founded in 2016 in Juba, South Sudan 
4. ATAKAHUB was founded in 2017 in Bor, South Sudan
5. Platform Africa was founded in 2017 in the Rhino camp refugee settlement in Uganda.
6.  YEF (Youth Empowerment Foundation) is an innovation hub in Uganda.


after discussion with Martin, he suggested to combine more the hubs as less points, rather than the timeline have each one as its own entry, and to focus on the years the workshops were done by R0g, with the hubs (pre-hubs) as such: 

2017 - 4 hubs Already launched and working, training participants in different skills. 

Any thoughts?

**Comment by yara89** [comment]
**2015** - The program started in South Sudan with the creation of a community-based media training center, Juba’s Open Knowledge and Innovation Hub (jHUB). The program has since evolved into a collection of smaller hubs and local initiatives in South Sudan and Uganda known as #ASKnet.

**2016**  - Pilot Workshop with trainers, 3 kits (#ASKotec) and 30 students was developed in Uganda.

**2017** - Four hubs Already established and launched; training participants in different skills.

**2019** - in the past three years, 25 trainings had been conducted with an average of 15 participants per training in the following regions: 
South Sudan: Juba, Yei, Bor  
Uganda: 2 refugee settlements (Kiryandongo, Rhino Camp)
Kenya: Nakuru, Nairobi
Ghana. Accra, Kumasi
Germany: Berlin

**2020** - 

**2021** -

**Comment by timmwille** [comment]
some history is also written connected to the ASKotec here if you scroll down:
https://openculture.agency/outcomes/askotec/

**Comment by timmwille** [comment]
**2015** - The program started in South Sudan with the creation of a community-based media training center, Juba’s Open Knowledge and Innovation Hub (jHUB). The program has since evolved into a collection of smaller hubs and local initiatives in South Sudan and Uganda known as #ASKnet.

2016 - Pilot Workshop with trainers, 3 kits (#ASKotec) and 30 students was developed in Uganda.

2017 - Four hubs Already established and launched; training participants in different skills. More emerging through initiatives of the "jHUB Pioneers" Community members

2018 - Intense trainings on organisational development and #OpenTech in Uganda Rhino Camp with the amazing Community Repair Café event kickoff

2019 - Trainings in Adjumnani on collaborative (online) Documentation and beyond in the past three years, 25 trainings had been conducted with an average of 15 participants per training in the following regions:
South Sudan: Juba, Yei, Bor
Uganda: 2 refugee settlements (Kiryandongo, Rhino Camp)
Kenya: Nakuru, Nairobi
Ghana. Accra, Kumasi
Germany: Berlin

2020 - Moving from the individual trainings with compact sessions to a more decentralized activity network with lots of trainings across Uganda, South Sudan and into virtual space with Remote Community Co-Creation and Repair Cafés as well as strong organisations emerging and forming new sattelites

2021 - story yet to be told, stay tuned

**Comment by timmwille** [comment]
2015 (better would be the picture from the energetic woman of the #peacehackcamp @intertwilight )
![2L0A3634](https://user-images.githubusercontent.com/8081055/146106208-f24b3b26-e666-415f-950f-54e564c82b28.JPG)

![DSC_9890](https://user-images.githubusercontent.com/8081055/146106678-8426ace9-7575-4c9e-aed5-2936a4add396.JPG)

![DSC_9790](https://user-images.githubusercontent.com/8081055/146106713-71d721c2-114c-417b-a50c-000ad42f09b4.JPG)



2016
![2L0A3841](https://user-images.githubusercontent.com/8081055/146106093-49e3278a-a9a9-47b3-ba4a-72b2beb156c8.JPG)

![2L0A3629](https://user-images.githubusercontent.com/8081055/146106546-e39d8c92-ec9e-4ab7-a012-96c5c7d75d8a.jpeg)

2017
![2L0A3838](https://user-images.githubusercontent.com/8081055/146106475-e563b450-7083-4323-858d-6751eb35471d.JPG)

![30516490_1792018260863044_3693724105657286656_o](https://user-images.githubusercontent.com/8081055/146106935-582142ae-b66a-4cc2-9f93-f73894686e18.jpg)

2018
![Uploading DSC_0343.JPG…]()

![DSC_0254](https://user-images.githubusercontent.com/8081055/146107491-11c13a35-68fe-4080-b05d-7b5eba5b735b.JPG)


2019

![DSC_0112](https://user-images.githubusercontent.com/8081055/146107570-b9cafbaf-2784-4ad7-ab69-af0ba1a9d0c1.JPG)


2020
![photo_2020-08-07_00-38-56](https://user-images.githubusercontent.com/8081055/146109117-b29d07bd-6dd6-4f74-854f-cf65dd9d1458.jpg)

![CommunityRepair-Example2-3](https://user-images.githubusercontent.com/8081055/146109273-cac40eb3-a38a-4af3-b045-38a88d9a3631.jpg)




2021

![photo_2019-10-31_01-19-01](https://user-images.githubusercontent.com/8081055/146108929-ee01c8fe-1f66-4adf-af2b-43f01cceddfc.jpg)

**Comment by timmwille** [comment]
![grafik](https://user-images.githubusercontent.com/8081055/146109453-d1f1d021-5b6d-452d-b778-f3c918359f53.png)
→ggf. 2020

**Comment by yara89** [comment]
@timmwille so, I added some photos let me know if some don't make sense with the year or you prefer another one to be displayed...

**Comment by timmwille** [comment]
Ok so we create a new version for the Beta as well, I'll move this ticket over later 

But the pictures are mixed up right now, so I hope it is not due to a merge conflict @MartinSchott @yara89 ?

I also forgot to add titles → so I think it would be best to have a short co-working sprint together!? when would be best? 1pm?

**Comment by MartinSchott** [comment]
can this be closed @timmwille ?

**Comment by timmwille** [comment]
the only thing missing is the + add new timeline event button, somehow went missing
