### ISSUE TITLE
Link License References to footer

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKnet-Website#64]
add License Text URLs

**Comment by timmwille** [comment]
@MartinSchott can you help me out here? what exactly would be my part? is info needed?

**Comment by MartinSchott** [comment]
I included the link to the MIT license for the theme (I linked to the license file which is in the repo of the theme - [here](https://github.com/raviriley/agency-jekyll-theme/blob/master/LICENSE.txt))

I also included the link to CC-BY-SA 4.0 (that license was already in place for the content) - [this link](https://creativecommons.org/licenses/by-sa/4.0/)

![grafik](https://user-images.githubusercontent.com/8080649/153450164-9b339058-735e-428c-80ef-7364992b38a9.png)

Because the link color is not dark enough for the white background, I changed the link color (for all links) to the darker brown 
→→ 
![grafik](https://user-images.githubusercontent.com/8080649/153450556-05fbe281-2e2f-4e73-8aad-7e2c6bbe5955.png)
